services:
  api:
    build: ./api
    container_name: api
    ports:
      - "8080:8080"
    volumes:
     - ./api:/api
     - ./api/node_modules:/api/node_modules
    networks:
      - romannumeralconverternetwork
    stdin_open: true
    tty: true
    command: npm run server

  client:
    build: ./client
    environment:
      - API_URL=http://api:8080
    container_name: client
    ports:
      - "3000:3000"
    volumes:
     - ./client:/client
     - ./client/node_modules:/client/node_modules
    networks:
      - romannumeralconverternetwork
    stdin_open: true
    tty: true
    command: npm run start
    links:
      - api
networks:
  romannumeralconverternetwork:
    driver: bridge
